### ISSUE TITLE
10MB limit in file input block element 

### ISSUE THREAD

**Issue by calereid-atria** [slackapi/bolt-python#1059] opened 2024-03-15 20:48 UTC
Tried to include a file input block in a Slack bot I'm building and stumbled upon the 10MB limit only after rolling out to production (was testing with a smaller file - admittedly my fault). 

This limit is not mentioned in the documentation: https://api.slack.com/reference/block-kit/block-elements#file_input

What is the reason for this limit? Especially given that I can share 1GB files throughout Slack otherwise. Are there workarounds to this?

**Comment by zimeg** [comment] 2024-03-15 22:18
Hey @calereid-atria! 👋  Sorry to hear you stumbled upon this limit! I'll share this with the team and look into adding it to documentation soon!

The initial reason for limiting file upload size is to prevent uploads from taking an unexpectedly long time in modals, but I agree this might not be ideal. A possible workaround might have users upload larger files via DM and download these based on a [`file_shared`](https://api.slack.com/events/file_shared) event using the `url_private_download` from [`files.info`](https://api.slack.com/methods/files.info) with your bot token.

I hope this is helpful and will get back to you with any updates, but please let me know if you have any other questions!

**Comment by calereid-atria** [comment] 2024-03-21 02:04
Hey @zimeg - thanks for the quick reply. Is there any way I could advocate (or gather support) for increasing this limit even  just to 100MB? It just doesn't make sense to me that I can upload 1GB elsewhere and only 10MB here

**Comment by zimeg** [comment] 2024-04-03 23:16
@calereid-atria thanks for the bump! Still pushing for this but the current concern is around long upload times with possibilities of having 10 file uploads in a single modal. At 100MB per file this can balloon into 1GB total upload sizes which can take a while for many folks.

Still hoping for increased upload sizes since I understand this is blocking for you, but I'll share anything definitive that we land on!

**Comment by zimeg** [comment] 2024-04-04 00:32
@calereid-atria the concern is mostly around the upload times happening in a focused modal instead of the message composer from what I can tell. I'm looking into possible workarounds for this right now though!

**Comment by zimeg** [comment] 2024-04-04 18:32
@calereid-atria I unfortunately don't think this will be changed anytime soon 😔 I know the workaround of accepting larger file uploads by DM is inconvenient at best, but I hope this might point towards possible ways of handling larger files.

Since no plans point towards changing this in the neartime I'll close this issue but will share any more updates I hear. For anyone following along and hoping for this, a 👍 on the issue is helpful for our prioritization on backend changes too!

**Closed by zimeg** 2024-04-04 18:32 UTC
Labels: question, server-side
