### ISSUE TITLE
app_mention and message event overlaps. 

### ISSUE THREAD

**Issue by JoselinSushma** [slackapi/bolt-python#941] opened 2023-08-01 17:36 UTC
### Reproducible in:
Events API, following fastapi example

#### The `slack_bolt` version

slack-bolt==1.18.0
slack-sdk==3.21.3

#### Python runtime version
Python 3.8.17

#### OS info
ProductName:            macOS
ProductVersion:         13.1
BuildVersion:           22C65
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

#### Steps to reproduce:

```python
from slack_bolt import App, Say
from slack_bolt.adapter.fastapi import SlackRequestHandler

bolt_app = App(token=app_config.SLACK_BOT_TOKEN, signing_secret=app_config.SLACK_SIGNING_SECRET)
bolt_app_handler = SlackRequestHandler(bolt_app)


@bolt_app.event("app_mention")
def handle_app_mentions(body, say, logger):
    logger.info(body)
    say("What's up?")


@bolt_app.event("message")
def handle_message(payload, say, logger, context):
    say("Test message received")
    pass


from fastapi import FastAPI, Request

api = FastAPI()


@api.post("/slack/events")
async def endpoint(req: Request):
    return await bolt_app_handler.handle(req)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(api, host="0.0.0.0", port=8000)
```

#### Run steps
1. run app.py
2. @mention slack app name from slack, 

### Expected result:

Only the code under @bolt_app.event("app_mention") handler should get invoked. 
Bot responds with "What's up?"

### Actual result:

code inside @bolt_app.event("message") also gets invoked with event['type'] as 'message'
Bot response : What's up?, Test message received

**Comment by seratch** [comment] 2023-08-02 00:40
Hi @JoselinSushma, thanks for asking the question. I understand that this could be confusing, but delivering the two types of events in this scenario is the expected behavior. Therefore, the recommended approach is to do nothing in the `app.event("message")` listener in this case. I hope you will find a suitable solution for your use case. Since we don't have anything further to share on this, let me close this issue now.

**Closed by seratch** 2023-08-02 00:40 UTC
Labels: question
