### ISSUE TITLE
Bolt for Python app_home_opened issue

### ISSUE THREAD

**Issue by ciubiu** [slackapi/bolt-python#226] opened 2021-01-28 17:56 UTC
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

I Followed webinar https://slack.com/intl/en-pl/events/webinars/building-on-the-slack-platform-with-python on Windows 10
and https://api.slack.com/start/building/bolt-python on Mac OS.
Everything else works, but app_home_opened get stuck somehow on both computers and bot's home tab says " This is still a work in progress" on both situations.

#### The `slack_bolt` version

slack_bolt v1.2.3

#### Python runtime version

python 3.9.1

#### OS info

Windows 10 & Mac os 10.16

#### Steps to reproduce:

Follow https://api.slack.com/start/building/bolt-python step by step.
Or follow webinar https://slack.com/intl/en-pl/events/webinars/building-on-the-slack-platform-with-python step by step and uncommenting / @app.event("app_home_opened") def publish_home_view(client, event, logger): / section in app.py file, enable specific event subscription.

### Expected result:

Opening bots home tab works as should.

### Actual result:

Bot's home tabs says " This is still a work in progress"

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment] 2021-01-29 23:21
@ciubiu 

>Bot's home tabs says " This is still a work in progress"

This means the home tab has been never been updated by `views.publish` API method calls.

I'd suggest to determine the problem this way:

* Does your app surely receive `app_home_opened` events from Slack?
  * If you use ngrok, you can check a list of HTTP requests your endpoint received at http://localhost:4040/inspect/http / if you are deploying your app to somewhere, check the web server's access logs
* If your endpoint is not receiving any `app_home_opened` requests, make sire if you add `app_home_opened` events in **Features** > **Event Subscriptions** > **Bot Events** in your app configuration page (https://api.slack.com/apps).
* If your endpoint is receiving events, check the errors in your app side.

**Comment by ciubiu** [comment] 2021-01-30 12:06
Thank you for the response. Today it started working and I did not change anything. It is strange, because I tried on Wednesday on Mac, Thursday on PC and now on Saturday it is somehow working. I did not change anything, I did not do anything differently, I just started my app and services. And now home tab is working.

**Comment by seratch** [comment] 2021-01-30 23:29
Thanks for sharing the updates. The cause is still unclear but I am glad to know your app is working now! Let me close this issue.

**Closed by seratch** 2021-01-30 23:29 UTC
Labels: area:sync, docs, question
