### ISSUE TITLE
app.action listener should accept block_id-only constraints for bolt-js feature parity

### ISSUE THREAD

**Issue by darkfoxprime** [slackapi/bolt-python#988] opened 2023-11-20 03:05 UTC
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

```
$ .venv/bin/pip freeze | grep slack
slack-bolt==1.18.0
slack-sdk==3.24.0
```

#### Python runtime version

```
$ .venv/bin/python --version
Python 3.9.16
```

#### OS info

(`sw_vers` is not valid in RHEL-related OSes)

```
$ cat /etc/redhat-release && uname -v
AlmaLinux release 9.2 (Turquoise Kodkod)
#1 SMP PREEMPT_DYNAMIC Tue Sep 12 09:28:32 EDT 2023
```

#### Steps to reproduce:

```python
@app.action( { 'type': 'block_action', 'block_id': 'response' } )
def handle_response_action(ack, client, body):
    pass
```

### Expected result:

Per the documentation...

>  You can use a constraints object to listen to `block_id`s and `action_id`s (or any combination of them).

Therefore, I expected to have an action handler that responded to any action from a block with id `response`.

### Actual result:

```
Failed to run a middleware (error: 'action_id')
Traceback (most recent call last):
  File "/home/darkfox/git/codeberg/darkfoxprime/FreeportTrawler/.venv/lib64/python3.9/site-packages/slack_bolt/app/app.py", line 534, in dispatch
    if listener.matches(req=req, resp=resp):
  File "/home/darkfox/git/codeberg/darkfoxprime/FreeportTrawler/.venv/lib64/python3.9/site-packages/slack_bolt/listener/listener.py", line 25, in matches
    is_matched = matcher.matches(req, resp)
  File "/home/darkfox/git/codeberg/darkfoxprime/FreeportTrawler/.venv/lib64/python3.9/site-packages/slack_bolt/listener_matcher/builtins.py", line 54, in matches
    return self.func(
  File "/home/darkfox/git/codeberg/darkfoxprime/FreeportTrawler/.venv/lib64/python3.9/site-packages/slack_bolt/listener_matcher/builtins.py", line 327, in func
    return _block_action(constraints, body)
  File "/home/darkfox/git/codeberg/darkfoxprime/FreeportTrawler/.venv/lib64/python3.9/site-packages/slack_bolt/listener_matcher/builtins.py", line 317, in _block_action
    action_id_matched = _matches(constraints["action_id"], action["action_id"])
KeyError: 'action_id'
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment] 2023-11-20 03:07
Hi @darkfoxprime, thanks for taking the time to share this feedback! Indeed, the document should clearly mention this. We will improve it later on. 

Since a block_actions event can occur per a block element w/ action_id, thie is by design. Thus, please set a unique action_id for each interactive block element in your blocks.

**Comment by darkfoxprime** [comment] 2023-11-20 03:47
> Hi @darkfoxprime, thanks for taking the time to share this feedback! Indeed, the document should clearly mention this. We will improve it later on.
> 
> Since a block_actions event can occur per a block element w/ action_id, thie is by design. Thus, please set a unique action_id for each interactive block element in your blocks.

The requirement for a "unique" `action_id` is exactly why I want to be able to add an action handler on the `block_id` instead.  My app uses dynamically-generated sets of actions, so it's impossible for me to be able to specify action ids for responding to them.  However, they all are contained within blocks with known block ids, so being able to use `@app.action( { 'block_id': '...' } )` with no `action_id` would greatly simplify this work.

**Comment by seratch** [comment] 2023-11-20 04:00
For this particular scenario, we currently recommend appending a prefix to the auto-generated action_id string values. Then pass a regexp that matches the prefix to an `app.action` listener. 

If we receive the same request more in the future (actually this is the first time to learn this need for us), we may consider enhancing the dictionary constraint to support only having block_id. However, I have to say that it's not our team's primary focus for us at this moment. It'd appreciated if you could understand this.

**Comment by darkfoxprime** [comment] 2023-11-20 04:02
In that case, please fix the documentation so that it clearly states that the `action_id` is required in the constraints.

**Comment by seratch** [comment] 2023-11-20 04:11
Hi @darkfoxprime, I am so sorry that I was wrong here. The document is in alignment with bolt-js, and the behavior of bolt-js is like you expect. Therefore, I must retract my above statement. We will improve bolt-python's behavior to be consistent with bolt-js. Though I'm presently occupied with a different task, I'm confident that I can make a new patch release including the fix for this issue within the next few business days.

**Closed** 2023-11-21 07:03 UTC
Labels: bug
