### ISSUE TITLE
The built-in installation store / state store using SQLAlchemy are not compatible with SQLAlchemy v2

### ISSUE THREAD

**Issue by joseph-scu** [slackapi/bolt-python#822] opened 2023-02-10 04:10 UTC
I am trying to create an app that implements OAuth. However, rather than using the `FileOAuthStateStore` that is outlined in the docs, I am trying to save the credentials/tokens etc to the database. I have been using [this](https://github.com/slackapi/bolt-python/blob/2216935b522dfc7f511e45252b76ffff5832ecb3/examples/sqlalchemy/oauth_app.py) as a guide to do so.

After implementing that code everything seemed to be working fine until I tried to install the app to the workspace from {my_route}/slack/install. I consistently get an Oops, Something Went Wrong! error page with the reason `invalid_state: The state parameter is no longer valid`.

Moreover, looking at my logs I have noticed the following error occur:

`WARNING:db:Failed to find any persistent data for state: e9b87291-2ec0-4842-b3e9-b95ee2f370ca - tuple indices must be integers or slices, not str`

I suppose then that the actual error is related to that `tuple indices must be integers or slices, not str` error message and not, in fact, related to invalid state.

Is there anything I could do from my end to fix this? 
Many thanks! :bow:

**Comment by seratch** [comment] 2023-02-10 04:24
Hi @joseph-scu, thanks a lot for taking the time to report this! I've confirmed the same error can arise on my end. The direct cause is SQLAlchemy's breaking change since their v2, which was recently released. We will resolve this issue in future versions, but until then, please use SQLAlchemy v1 instead.

**Comment by joseph-scu** [comment] 2023-02-10 05:26
Thank you for the speedy response! Understood, I will use an earlier version of SQLAlchemy in the meantime then.

**Comment by seratch** [comment] 2023-02-17 06:25
Resolved by https://github.com/slackapi/python-slack-sdk/releases/tag/v3.20.0 release

**Closed by seratch** 2023-02-17 06:25 UTC
Labels: bug, improvement
