### ISSUE TITLE
Slack Event sending fake message_changed when writing to bot directly when Also send as direct message is enabled

### ISSUE THREAD

**Issue by aghabekyan101214** [slackapi/bolt-python#919] opened 2023-06-16 07:58 UTC
Version of Slack Bolt = 1.18.0
Bot Events Subscribed:
app_mention, message.im

Direct messages your app sends will show in this tab - this should be enabled

Steps how I replicate:
1) Navigate to the Apps section on left panel and find the APP
2) Click on the app name and write smth
3) An event triggers my endpoint and I answer it using slack_sdk chat_postMessage (channel=channel, text=message, thread_ts=ts). 
4) The new message sent from 3d step appears in Slack. After this just for testing purposes I comment my codes which are responsible for sending message to slack (so this won't be triggered chat_postMessage (channel=channel, text=message, thread_ts=ts) )
5) I open the thread, write there something, check "Also send as direct message" and send the message

Note! This happens only when you directly write to the bot.
When the bot is in a public channel, everything works as expected.

After sending the message, my endpoint receives 2 message events:
First one: subtype = thread_broadcast
Second one:  subtype = message_changed

Referring to this documentation (https://api.slack.com/events/message/message_changed), message_changed would be triggered when using chat.update.

Please help me to figure this out. Thanks

**Comment by seratch** [comment] 2023-06-16 08:34
Hi @aghabekyan101214, thanks for writing in!

I've confirmed that the situation you've described can indeed occur in my sandbox workspace. The only difference is that the two subtype message events can also be sent for channel messages, not just DMs with a bot. So, in my observation, this is not specific to bot DMs.

I am confident that this did not happen in the past. It's possible that some changes on the server-side may have introduced this behavior. We can report this unintuitive behavior to our server-side engineering teams internally, but we cannot guarantee when or if this issue will be addressed.

As a workaround, please consider ignoring the "message_changed" events for now. In this scenario, `event.message.subtype` in the payload is always "thread_broadcast", so you can easily skip processing the unnecessary event data by checking the combination of `event.subtype` and `event.message.subtype`.

I hope this helps.

**Comment by aghabekyan101214** [comment] 2023-06-16 08:42
Thanks @seratch for the fast reply. Hope this issue will be solved soon.

**Comment by seratch** [comment] 2023-06-16 08:52
Thanks for your reply. Since this is the issue tracker for bolt-python library, we are unable to deliver timely updates on the server-side issues. Let us close this issue now. For the updates on the issue, please contact our customer support agents. Thanks again for taking the time to report this, and we are sorry for the inconvenience.

**Closed by seratch** 2023-06-16 08:52 UTC
Labels: question, server-side
