### ISSUE TITLE
Problem with globals in socketmode + flask

### ISSUE THREAD

**Issue by De1f364** [slackapi/bolt-python#350] opened 2021-05-25 13:34 UTC
Hi! I use SocketMode in my application in conjunction with Flask, in order to make a health check of the probes, so I use in this form:
```bash
@flask_app.route('/readiness')
def readiness():
    return {"status": "Ok"}


if __name__ == "__main__":
    SocketModeHandler(app, settings.slack_app_token).connect()
    flask_app.run(host="0.0.0.0", port=14111, threaded=True, debug=True)
```
but in this case, for some reason, my global variables in the application are periodically lost between calls to actions.

When I use it like this without Flask, everything works fine, but I need this health check probe
```bash
if __name__ == "__main__":
    SocketModeHandler(app, settings.slack_app_token).start()
```
What could be the reason? And how can you get around this?
#### The `slack_bolt` version

slack-bolt==1.4.4
slack-sdk==3.4.2

#### Python runtime version

Python 3.8.2

#### OS info

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
Darwin Kernel Version 19.6.0

**Comment by seratch** [comment] 2021-05-25 13:41
Hi @De1f364, thanks for asking the question!

> my global variables

Can you share the part in your code? If you provide a minimum working example reproducing your situation, others may be able to help you out more easily.

**Comment by De1f364** [comment] 2021-05-25 14:40
```bash
from slack_bolt import App, Ack
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_sdk import WebClient
from slack_bolt.adapter.flask import SlackRequestHandler
from flask import Flask
from slack_sdk.errors import SlackApiError

from src.settings import Settings
from src.utils import get_results, jira_generator_priority, jira_tasks
from src.logger import get_logger
from resources2 import priority_select, res_button


flask_app = Flask(__name__)
logger = get_logger('main')
settings = Settings()
app = App(token=settings.slack_bot_token)
handler = SlackRequestHandler(app)

msg_for_thread = ""
pretext_priority = ""
pretext_time = ""
current_task = ""
vote_results = {}
tasks_gen_prior = jira_generator_priority()


def start_voting(client: WebClient, user: str, channel: str, blocks: dict) -> None:
    global msg_for_thread, current_task
    task_for_vote = next(tasks_gen_prior)
    blocks[1].text.text = f"{task_for_vote} {jira_tasks.task_name(task_for_vote)} " \
                          f"{jira_tasks.task_url(task_for_vote)}"
    current_task = blocks[1].text.text
    if msg_for_thread:
        client.chat_update(
            channel=channel,
            ts=msg_for_thread,
            as_user=True,
            blocks=blocks,
            attachments=[{"pretext": ""}]
        )
    else:
        voting = client.chat_postMessage(channel=settings.slack_channel,
                                         text="voting",
                                         blocks=blocks)
        msg_for_thread = voting["ts"]
        client.chat_postEphemeral(channel=settings.slack_channel,
                                  blocks=res_button["blocks"],
                                  user=user)


@app.command("/priority")
def go_priority(ack: Ack, client: WebClient, body: dict) -> None:
    global tasks_gen_prior, msg_for_thread
    ack()
    msg_for_thread = ""
    tasks_gen_prior = jira_generator_priority()
    start_voting(client, body["user_id"], body["channel_id"], priority_select["blocks"])


@app.action("priority_select-action")
def card_chosen_priority(ack: Ack, body: dict, client: WebClient) -> None:
    global pretext_priority, vote_results
    ack()
    vote_results[body['user']['username']] = body['actions'][0]['selected_option']['text']['text']
    if body["user"]["username"] not in pretext_priority:
        pretext_priority += f'<@{body["user"]["username"]}> '
    try:
        res = client.chat_update(
            channel=body["channel"]["id"],
            ts=msg_for_thread,
            as_user=True,
            text="Updating msg",
            attachments=[{"pretext": f"{pretext_priority}"}]
        )
        logger.info(res)
    except SlackApiError as e:
        raise e


@app.action("results")
def show_results(ack: Ack, client: WebClient, body: dict) -> None:
    global vote_results, pretext_priority, pretext_time, current_task
    ack()
    results = get_results(vote_results)
    client.chat_update(
        channel=body["channel"]["id"],
        ts=msg_for_thread,
        as_user=True,
        attachments=[{"pretext": f"{results}"}]
    )


@flask_app.route('/system/readiness')
def readiness():
    return {"status": "Ok"}


if __name__ == "__main__":
    SocketModeHandler(app, settings.slack_app_token).connect()
    flask_app.run(host="0.0.0.0", port=14111, threaded=True, debug=True)
```
Here is a part of the code, here when @ app.action ("results") is called, then
the global variable msg_for_thread is often empty and works normally only after a few clicks on this button. 
But if you remove flask, then everything works fine

**Comment by seratch** [comment] 2021-05-26 02:19
@De1f364 
At first glance, I'm not sure what the root cause of the inconsistent global values is yet. As far as I know, the only thing very specific to Flask is the framework's wide usage of thread-locals: https://flask.palletsprojects.com/en/1.1.x/advanced_foreword/#thread-locals-in-flask I've never heard of issues about global variables.

As a general recommendation, I really don't recommend using pretty simple global variables for managing user states. If you use globals, at least using a dict like `{"user_id_1": "xxx", "user_id_2": "yyy"}` would be safer for avoiding mixing the states among multiple users. It's generally hard to safely manage global variables. I'm afraid that some parts of your code may be doing something unexpected.

**Comment by De1f364** [comment] 2021-05-26 10:01
@seratch 
Thanks for the answer! Is there a way in bolt-python to store information between actions? Session or cache?

**Comment by seratch** [comment] 2021-05-26 11:07
@De1f364 There is no built-in support for it. You can store data associated with users into database as necessary.

**Comment by De1f364** [comment] 2021-05-26 11:28
@seratch I need to store not user information, but the timestamp of the message between calls to update it

**Comment by seratch** [comment] 2021-05-26 11:35
Either way, you can store any data in database. You can do anything in your listener functions. Do you have anything further to ask? If not, would you mind closing this issue?

**Closed** 2021-05-26 11:41 UTC
Labels: area:adapter, question
