### ISSUE TITLE
Built-in Flask adapter does not work for AsyncApp

### ISSUE THREAD

**Issue by romanguirbal** [slackapi/bolt-python#1115] opened 2024-08-01 14:50 UTC
The following error is happening when my async app receives any event, although installation step works fine:

```
[DEBUG] - No installation data found for enterprise_id: None team_id: redacted
ERROR:slack_bolt.AsyncMultiTeamsAuthorization:Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found.
ERROR:slack_bolt.AsyncApp:Failed to run a middleware function (error: object WebhookResponse can't be used in 'await' expression)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slack_bolt/app/async_app.py", line 548, in async_dispatch
    resp = await middleware.async_process(req=req, resp=resp, next=async_middleware_next)
  File "/usr/local/lib/python3.10/dist-packages/slack_bolt/middleware/authorization/async_multi_teams_authorization.py", line 100, in async_process
    await req.context.respond(self.user_facing_authorize_error_message)
TypeError: object WebhookResponse can't be used in 'await' expression
44.201.112.10 - - [01/Aug/2024:14:09:34 +0000] "POST /slack/events HTTP/1.1" 500 0 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
```

To me it seems that one of the middlewares (AsyncMultiTeamsAuthorization) is failing for reasons yet to be determined so the authorization step fails and returns None.

#### Extra information:

I do not know yet if the following information is relevant or not, that is why I included it here:
I am using some async code in event handlers so I had to use AsyncApp instead of App.
Since this slack app is integrated into a broader Flask app, I had to use the Flask adapter, but given the fact I am using AsyncApp and I did not found an async Flask adapter, I had to make a custom one, almost identical to the normal one.

#### The `slack_bolt` version

slack_bolt==1.19.1
slack_sdk==3.27.2

#### Python runtime version

Python 3.12.4

#### OS info

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Take async app example from samples folder
2. Reproduce the same setup as mentioned above (samples of code below)
3. Install app to workspace
4. In Slack client try the /help command
5. See the error mentioned above

```python
slack_app = AsyncApp(
    oauth_settings=oauth_settings,
    signing_secret=slack_config.signing_secret
)

slack_app.logger.setLevel("DEBUG") # TODO: remove

_register_oauth_routes(app)

handler = AsyncSlackRequestHandler(slack_app)

# Register routes to Flask app
@app.route("/slack/events", methods=["POST"])
async def slack_events():
    # handler runs App's dispatch method
    return await handler.handle(request)
```

```python
class AsyncSlackRequestHandler:
    def __init__(self, app: AsyncApp):  # type: ignore
        self.app = app

    async def handle(self, req: Request) -> Response:
        if req.method == "GET":
            if self.app.oauth_flow is not None:
                oauth_flow: OAuthFlow = self.app.oauth_flow
                if req.path == oauth_flow.install_path:
                    bolt_resp = oauth_flow.handle_installation(to_bolt_request(req))
                    return to_flask_response(bolt_resp)
                elif req.path == oauth_flow.redirect_uri_path:
                    bolt_resp = oauth_flow.handle_callback(to_bolt_request(req))
                    return to_flask_response(bolt_resp)
        elif req.method == "POST":
            bolt_resp: BoltResponse = await self.app.async_dispatch(to_bolt_request(req))
            return to_flask_response(bolt_resp)

        return make_response("Not Found", 404)
```

```python
@app.command("/help")
async def handle_help_command(ack, say, command):
    await ack()
    await say("This is the help message")
    return
```

### Expected result:

Authorization step pass, installation is retrieved (it exists) and the request can be processed by event handler.

### Actual result:

Following error
```
ERROR:slack_bolt.AsyncApp:Failed to run a middleware function (error: object WebhookResponse can't be used in 'await' expression)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slack_bolt/app/async_app.py", line 548, in async_dispatch
    resp = await middleware.async_process(req=req, resp=resp, next=async_middleware_next)
  File "/usr/local/lib/python3.10/dist-packages/slack_bolt/middleware/authorization/async_multi_teams_authorization.py", line 100, in async_process
    await req.context.respond(self.user_facing_authorize_error_message)
TypeError: object WebhookResponse can't be used in 'await' expression
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment] 2024-08-01 16:57
Thanks for writing in @romanguirbal 💯 

Its seems like your implementation of the Flask `AsyncSlackRequestHandler` may not work properly. Based on a quick research Flask seems to support [async python](https://flask.palletsprojects.com/en/3.0.x/async-await/) but I am not familiar with it.

Is the broader Flask application where the Bolt App will be deployed configured to support `async` python? ([ASGI](https://flask.palletsprojects.com/en/3.0.x/deploying/asgi/))

Comparing your implementation to other `async` adapters like the [starlette one](https://github.com/slackapi/bolt-python/blob/main/slack_bolt/adapter/starlette/async_handler.py#L48) it seems like `oauth_flow` request handlers must also be awaited, you may also need to implement your own `to_bolt_request` and `to_flask_response`

```python
class AsyncSlackRequestHandler:
    def __init__(self, app: AsyncApp):  # type: ignore
        self.app = app

    async def handle(self, req: Request) -> Response:
        if req.method == "GET":
            if self.app.oauth_flow is not None:
                oauth_flow: OAuthFlow = self.app.oauth_flow
                if req.path == oauth_flow.install_path:
                    bolt_resp = await oauth_flow.handle_installation(to_bolt_request(req))
                    return to_flask_response(bolt_resp)
                elif req.path == oauth_flow.redirect_uri_path:
                    bolt_resp = await oauth_flow.handle_callback(to_bolt_request(req))
                    return to_flask_response(bolt_resp)
        elif req.method == "POST":
            bolt_resp: BoltResponse = await self.app.async_dispatch(to_bolt_request(req))
            return to_flask_response(bolt_resp)

        return make_response("Not Found", 404)
```

I will label this as a potential feature request to support ASGI + Flask

**Comment by seratch** [comment] 2024-08-02 03:10
@romanguirbal Thanks for sharing this. 

As @WilliamBergamin mentioned, the built-in Flask adapter does not support asyncio interface, thus you need to write your own adapter code that is compatible with async/await nature. With that being said, I generally don't recommend the async/await way with Flask. [Flask's document page clearly says there is no performance benefit with it](https://flask.palletsprojects.com/en/3.0.x/async-await/#performance) as it just spins up a new event loop for each worker thread that handles a request. Also, [you cannot start a new async task within the handler code, so instead you need a queue to enable a different process with a long-running event loop to receive async tasks](https://flask.palletsprojects.com/en/3.0.x/async-await/#background-tasks).  Especially, the second point could be an unpleasant pitfall for your app development in the future.

If you need to run asyncio code, I recommend going with any of startlette, fastapi, sanic, and whatever natively supports event-loop IO. bolt-python provides adapters for these frameworks. Also, since `App` and its listener mechanism is completely framework-agnostic, choosing a different web framework does not require any code change in your listeners. Nonetheless, if you still want to use Flask asyncio while you understand its downsides, it's your decision.

@WilliamBergamin Indeed, technically it's feasible to add built-in adapter for Flask asyncio apps, but I personally hesitate to add such because I really don't recommend using it for Bolt apps. For this reason, let me remove the "enhancement" tag and set "question" to this issue instead.

I hope this clarifies things.

**Comment by seratch** [comment] 2024-08-02 13:13
>Do you know if there is a way to achieve the same goal but avoiding the downsides and pitfalls you mentioned ?

As I mentioned above, using Flask for async/await code is not a common approach at all, so I don't recommend it. You may face unexpected pitfalls along the way. You may have to debug your code carefully when you experience such (generally speaking, debugging asyncio code to identify unexpected behaviors is hard). However, if you understand the things described in Flask's document page and you don't see any major problems with it, you can go ahead with it. It's up to you! You can achieve your goal as long as you're aware of the limitations that Flask's asyncio support has.

It seems that all the points to discuss on this topic are already covered, so let me close this issue now. Good luck with your Slack app development!

**Closed by seratch** 2024-08-02 13:13 UTC
Labels: question, area:async

**Comment by romanguirbal** [comment] 2024-08-02 15:17
Thank you for your time and your answers !
