### ISSUE TITLE
Lazy modal submission not working as expected.

### ISSUE THREAD

**Issue by kevgliss** [slackapi/bolt-python#791] opened 2022-12-16 18:14 UTC
My modal submission events often exceed the three second time limit, but using lazy listeners does not seem to be correctly acknowledging my requests. 

### Reproducible in:

slack-bolt==1.15.5
slack-sdk==3.19.1
Python 3.9.7
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380

#### Steps to reproduce:

```python
app = AsyncApp(
    token="xoxb-valid", raise_error_for_unhandled_request=True
)

async def ack_shortcut(ack):
    await ack()


async def open_modal(body, client):
    await client.views_open(
        trigger_id=body["trigger_id"],
        view={
            "type": "modal",
            "callback_id": "socket_modal_submission",
            "submit": {
                "type": "plain_text",
                "text": "Submit",
            },
            "close": {
                "type": "plain_text",
                "text": "Cancel",
            },
            "title": {
                "type": "plain_text",
                "text": "Socket Modal",
            },
            "blocks": [
                {
                    "type": "input",
                    "block_id": "q1",
                    "label": {
                        "type": "plain_text",
                        "text": "Write anything here!",
                    },
                    "element": {
                        "action_id": "feedback",
                        "type": "plain_text_input",
                    },
                },
                {
                    "type": "input",
                    "block_id": "q2",
                    "label": {
                        "type": "plain_text",
                        "text": "Can you tell us your favorites?",
                    },
                    "element": {
                        "type": "external_select",
                        "action_id": "favorite-animal",
                        "min_query_length": 0,
                        "placeholder": {
                            "type": "plain_text",
                            "text": "Select your favorites",
                        },
                    },
                },
            ],
        },
    )


app.shortcut("socket-mode")(ack=ack_shortcut, lazy=[open_modal])

all_options = [
    {
        "text": {"type": "plain_text", "text": ":cat: Cat"},
        "value": "cat",
    },
    {
        "text": {"type": "plain_text", "text": ":dog: Dog"},
        "value": "dog",
    },
    {
        "text": {"type": "plain_text", "text": ":bear: Bear"},
        "value": "bear",
    },
]


@app.options("favorite-animal")
async def external_data_source_handler(ack, body):
    keyword = body.get("value")
    if keyword is not None and len(keyword) > 0:
        options = [o for o in all_options if keyword in o["text"]["text"]]
        await ack(options=options)
    else:
        await ack(options=all_options)


# throws an error if processing takes too long
async def submission():   
    import time
    time.sleep(10)      

app.view("socket_modal_submission")(ack=ack_shortcut, lazy=[submission])

async def main():
        handler = AsyncSocketModeHandler(
            app, token
        )
        await handler.start_async()

asyncio.run(main())
```

### Expected result:

I would expect to be able to run `submission` function without the modal displaying an error about related to the connection timing out.

### Actual result:

The submission function does not seem to be lazy (if it takes longer than 3 seconds to run the modal displays and error)
![Screenshot 2022-12-16 at 10 10 59 AM](https://user-images.githubusercontent.com/2262214/208162080-e8554a10-6828-46eb-b036-ecd407efe449.png)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment] 2022-12-16 18:47
Hi @kevgliss, can I double-check that you have `process_before_response=true`? 

``
# process_before_response must be True when running on FaaS
app = App(process_before_response=True)
```

**Comment by kevgliss** [comment] 2022-12-16 19:14
@srajiang I did not set that setting. My understanding was that it was mainly for the lambda use case that terminated a process after sending a HTTP response. In my case I am use the async websocket app. 

As percaution, I did try it with that setting enabled, but `submission` function is never called.  

I've updated my example with the app handlers that I am using.

**Comment by seratch** [comment] 2022-12-16 23:37
Hey @kevgliss, the cause is your `time.sleep` call in the lazy listener. As you may know, asyncio is a single-threaded event-loop model. So using a blocking code can very easily cause this type of critical problem for the entire app. Your demo code needs to be something like this:

```python
async def submission():
    import asyncio
    await asyncio.sleep(10)
```

**Comment by kevgliss** [comment] 2022-12-19 18:51
Ah, I see. We were previously using https://www.starlette.io/background/, which typically hides this complexity from us. I thought `lazy` as means for running long-running tasks might function similarly (e.g. by creating an executor), but that was an incorrect assumption on my part. I see now that `lazy` is really only responsible for breaking up the `ack` lifecycle.

**Comment by seratch** [comment] 2022-12-19 22:47
Thanks for sharing that. Adding something more sophisticated, like the background tasks by FastAPI, may be worth exploring in the future. It seems that everything is clear on the topic here. Let me close this issue now.

**Closed by seratch** 2022-12-19 22:47 UTC
Labels: question, area:async
