### ISSUE TITLE
Error in chat_postMessage method

### ISSUE THREAD

**Issue by soilmo** [slackapi/bolt-python#1016] opened 2024-01-17 18:59 UTC
I tried the following code:

```
block = [{"type": "section","text": {"type": "mrkdwn","text": "Erro na consulta " + str(datetime.now())}}]
client_bot.chat_postMessage(channel=channel_id, blocks = block)
```

And i got the answer:

```
Failed to run listener function (error: The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['invalid_url [json-pointer:/blocks/0/slack_file.url]'], 'response_metadata': {'messages': ['[ERROR] invalid_url [json-pointer:/blocks/0/slack_file.url]']}})
```

This same code ran successfully about four hours earlier, but now it has this error.

Can anyone help me?

**Comment by filmaj** [comment] 2024-01-17 19:48
Hey @soilmo , we are investigating this. We are seeing elevated rates of this error; our engineering teams are looking into the issue. Once I have more info I'll post here again.

**Comment by soilmo** [comment] 2024-01-17 20:02
Thanks! I'll be waiting for good news.

**Comment by filmaj** [comment] 2024-01-17 20:49
@soilmo I can't reproduce the error you are seeing with the payload you provided in your original post. Are you still seeing this?

**Comment by soilmo** [comment] 2024-01-17 20:59
@filmaj i tried again and got the same error.

Let me explain better about my situation:

I created a slack bot using Slack Bolt. It works well, but today after lunch, some functions doesn't work. All functions the send images happened this problem.

See print below to understand better:

![image](https://github.com/slackapi/bolt-python/assets/60858896/19418f91-5767-498d-a201-14483bec89aa)

**Comment by soilmo** [comment] 2024-01-17 21:06
Sure!

The block is below:
```

say(

            blocks = [
                
                {
                    "type": "section",
                    "text": {
                        "type": "plain_text",
                        "text": 'Última atualização: '+str(infos[1])+' '+str(infos[2]) + ' | ITD do IPCA é o mesmo do FOCUS FIC FIA (2020-12-28)'
                    },
                    "accessory": {
                        "type": "image",
                        "slack_file": {
                            "url": infos[0]
                        },
                        "alt_text": "Rentabilidades"
                    }
                }
            ]
        )
```

Where:

`infos[0] = "https://files.slack.com/files-pri/T01J6BY2VEU-F06ERESRXUZ/rentabilidades.png?pub_secret=aa3396340f"`

**Comment by filmaj** [comment] 2024-01-17 21:10
Whoa, you're already using `"slack_file": { "url": infos[0] }`? We just released that as a brand new feature, like, 4 hours ago?

**Comment by filmaj** [comment] 2024-01-17 21:12
We believe the issue may be the `pub_secret` querystring param. Try dropping that?
Also: where are you getting that URL from?

**Comment by soilmo** [comment] 2024-01-17 21:16
Nice! Exactly! My problem was started about 4 hours ago.

My URL is been created like this:

```

        client = WebClient(token=SLACK_USER_OAUTH_TOKEN)
        
        result = client.files_upload(channel=channel_id,file=path, initial_comment = 'Carteira')
        result_url = client.files_sharedPublicURL(file = result['file']['id'])

        website = result_url['file']['permalink_public'].split("https://slack-files.com/")[1]
        team_id = website.split('-')[0]
        file_id = website.split('-')[1]
        pub_secret = website.split('-')[2]
        filename = result_url['file']['name']
        direct_link = "https://files.slack.com/files-pri/" + team_id + "-" + file_id + "/" + filename + "?pub_secret=" + pub_secret
```
Your suggest is do the following?

```

        client = WebClient(token=SLACK_USER_OAUTH_TOKEN)
        
        result = client.files_upload(channel=channel_id,file=path, initial_comment = 'Carteira')
        result_url = client.files_sharedPublicURL(file = result['file']['id'])

        website = result_url['file']['permalink_public'].split("https://slack-files.com/")[1]
        team_id = website.split('-')[0]
        file_id = website.split('-')[1]
        filename = result_url['file']['name']
        direct_link = "https://files.slack.com/files-pri/" + team_id + "-" + file_id + "/" + filename
```

**Comment by soilmo** [comment] 2024-01-17 21:44
Sure! I appreciate contribute into this task!

But i dont fix error yet. Now, i tried like this:

```
client = WebClient(token=SLACK_USER_OAUTH_TOKEN)

result = client.files_upload(channel=channel_id,file=path, initial_comment = 'Rentabilidades')
result_url = client.files_sharedPublicURL(file = result['file']['id'])

website = result_url['file']['permalink']
print(website)
```
And the block used was:
```

say(

            blocks = [
                
                {
                    "type": "section",
                    "text": {
                        "type": "plain_text",
                        "text": 'Última atualização: '+str(infos[1])+' '+str(infos[2]) + ' | ITD do IPCA é o mesmo do FOCUS FIC FIA (2020-12-28)\n'
                    },
                    "accessory": {
                        "type": "image",
                        "slack_file": {
                            "url": infos[0]
                        },
                        "alt_text": "Rentabilidades"
                    }
                }

                
            ]
        )
```
I got the same error:

![image](https://github.com/slackapi/bolt-python/assets/60858896/a4a23a86-d22c-4c09-a96f-8917420e6072)

**Comment by filmaj** [comment] 2024-01-17 21:48
OK, different error.

What is the value of `infos[0]` in your example?

**Comment by filmaj** [comment] 2024-01-17 22:05
What kind of token is being used? A bot token or a user token? Does your app implement OAuth flow to retrieve user tokens to make actions on behalf of a user?

**Comment by soilmo** [comment] 2024-01-17 22:11
I use a bot token to create WebClient object and Bot User OAuth Token when i upload image on slack cloud.

Maybe use these differents codes in the same bot can make this error.

**Comment by filmaj** [comment] 2024-01-17 22:14
That's a bit of a confusing answer  😅 What I need to know is, do you use an `xoxb-...` or an `xoxp-...` token for each of the different Slack API calls? (files.upload, files.sharedPublicURL, chat.postMessage)

**Comment by soilmo** [comment] 2024-01-17 22:16
Oh, sorry. But yes. Let me show you:

SLACK_BOT_TOKEN: xoxb-...
SLACK_USER_OAUTH_TOKEN: xoxp-...

![image](https://github.com/slackapi/bolt-python/assets/60858896/1ab17aca-54eb-49f0-94ba-05cfc4d61f1c)

![image](https://github.com/slackapi/bolt-python/assets/60858896/1fbe4937-50c4-44e6-84fe-5b1651f0812c)

**Comment by filmaj** [comment] 2024-01-17 22:18
OK great, that's what I needed to know. And for the `chat.postMessage` API, which token is used?

**Comment by soilmo** [comment] 2024-01-18 13:06
@filmaj i solved!! :)

I just use the same token at the following parts:

Starting bot at the beggining of code:
![image](https://github.com/slackapi/bolt-python/assets/60858896/26d75859-68ce-4038-b8e2-969fe2fea891)

Upload file (image) in slack cloud.
![image](https://github.com/slackapi/bolt-python/assets/60858896/01c8ba6f-ab0d-48af-8e26-0cacd18b5839)

And for send file, i used the method below:

![image](https://github.com/slackapi/bolt-python/assets/60858896/64f16e8a-2f31-45d3-86f1-437928a189a8)

**Comment by filmaj** [comment] 2024-01-18 13:59
Glad you got it fixed!

FYI, we actually will be rolling back the new `slack_file` property / feature of image blocks today due to various issues it caused for customers (including the problem you experienced earlier). So please continue using the `image_url` property as I see you are doing in your last screenshot for the time being.

I will close this issue now but if you have further issues here, feel free to re-open or file a new issue.

**Closed by filmaj** 2024-01-18 13:59 UTC
Labels: bug, question, server-side

**Comment by soilmo** [comment] 2024-01-22 12:49
Hi!

The same error is happening again.
