### ISSUE TITLE
Why am I getting a 'not_allowed_token_type' error from the Slack API?

### ISSUE THREAD

**Issue by chxw** [slackapi/bolt-python#374] opened 2021-06-08 20:16 UTC
I am trying to open a modal when a user clicks my app's **Global shortcut.** 

![Screen Shot 2021-06-08 at 4 01 44 PM](https://user-images.githubusercontent.com/48259059/121249670-d62c8180-c872-11eb-9966-8d9221412180.png)

But when I try, I receive the following error message:
```
127.0.0.1 - - [08/Jun/2021 15:54:37] "POST /slack/events HTTP/1.1" 200 -
Error creating conversation: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'not_allowed_token_type'}
```

I'm not sure what the source of the issue is, since I am able to successfully use a separate function (`update`) to collect the text of a slack message when a user mentions my app (see `@app.event("app_mention")`. 

Note: In both Interactivity & Shortcuts and Event Subscriptions, both the Request URLs are my ngrok.io link at `/slack/events` (i.e. `https://...ngrok.io/slack/events`) 

I also checked in previously logged issues on this github, and saw [this](https://github.com/slackapi/bolt-python/issues/305). Afterwards, I checked the `views.open` method page [here](https://api.slack.com/methods/views.open) and see that it works with both **bot** and **user** token types with no scopes required. 
![Screen Shot 2021-06-08 at 4 06 34 PM](https://user-images.githubusercontent.com/48259059/121250453-bba6d800-c873-11eb-90b0-9a5c4542f425.png)

What am I doing wrong?

#### The `slack_bolt` version
slack-bolt==1.6.1
slack-sdk==3.6.0
slackclient==2.9.3
slackeventsapi==2.2.1

#### Python runtime version
Python 3.9.2

#### OS info
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64

#### Steps to reproduce:

1. source venv/bin/activate
2. python3 main.py
3. ./ngrok http 3000
4. Click shortcut using Bolt icon. 
![Screen Shot 2021-06-08 at 3 59 48 PM](https://user-images.githubusercontent.com/48259059/121249408-8fd72280-c872-11eb-97b1-3fbd0f2513f7.png)

**Source code:**
.env
```bash
export MONDAY_API_KEY="..."
export SLACK_BOT_TOKEN="xoxb-..."
export SLACK_SIGNING_SECRET="..."
```

main.py
```python
import os
# Use the package we installed
from slack_bolt import App
from slack_sdk.errors import SlackApiError
import requests
import json

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

@app.event("app_mention")
def update(client, event, logger):
    try:
        apiKey = os.environ.get("MONDAY_API_KEY")
        apiUrl = "https://api.monday.com/v2"
        headers = {"Authorization" : apiKey}
        board_id = "1029994357"
        query5 = 'mutation ($myItemName: String!, $columnVals: JSON!) { create_item (board_id:'+board_id+', item_name:$myItemName, column_values:$columnVals) { id } }'
        vars = {
        'myItemName' : event["blocks"][0]["elements"][0]["elements"][1]["text"]
        }
        data = {'query' : query5, 'variables' : vars}
        r = requests.post(url=apiUrl, json=data, headers=headers) # make request
        print(r.json())
    except Exception as e:
        logger.error(f"Error publishing home tab: {e}")

# The open_modal shortcut listens to a shortcut with the callback_id "open_modal"
@app.shortcut("file_bug")
def open_modal(ack, shortcut, client, logger, body):
    # Acknowledge the shortcut request
    ack()

    try:
        # Call the views_open method using the built-in WebClient
        api_response = client.views_open(
            trigger_id=shortcut["trigger_id"],
            # A simple view payload for a modal
            view=
                {
                    "title": {
                        "type": "plain_text",
                        "text": "File a bug",
                        "emoji": True
                    },
                    "submit": {
                        "type": "plain_text",
                        "text": "Submit",
                        "emoji": True
                    },
                    "type": "modal",
                    "close": {
                        "type": "plain_text",
                        "text": "Cancel",
                        "emoji": True
                    },
                    "blocks": [
                        {
                            "type": "section",
                            "text": {
                                "type": "plain_text",
                                "text": "This form will submit your bug to the #dev-bugs board on monday.com",
                                "emoji": True
                            }
                        }
                }
        logger.info(api_response)
    except SlackApiError as e:
        logger.error("Error creating conversation: {}".format(e))
    
# Start your app
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

### Expected result:
Modal is opened, as shown in ["Modal Preview"](https://app.slack.com/block-kit-builder/TMDTWEGDN#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Add%20info%20to%20feedback%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Save%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22blocks%22:%5B%5D%7D) in Block Kit Builder. 

### Actual result:
Error message in terminal tab running bolt app:
```
127.0.0.1 - - [08/Jun/2021 15:54:37] "POST /slack/events HTTP/1.1" 200 -
Error creating conversation: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'not_allowed_token_type'}
```

Error message in Slack app:
![Screen Shot 2021-06-08 at 4 00 06 PM](https://user-images.githubusercontent.com/48259059/121249455-99f92100-c872-11eb-9373-9b9fc2752a25.png)

**Comment by mwbrooks** [comment] 2021-06-08 22:14
Hey @chxw, thanks a bunch for the detailed issue!

☑️ You're right that `views.open` should work with either a bot or user token. And it looks like you're using the bot token right now (`xoxb-`).

☑️ I was also able to setup your example on my local machine and open the modal successfully. _(I just had to edit a typo in the `views=` and I used SocketMode instead of ngrok)._ So, everything looks good at a glance!

**Would you mind double-checking your `SLACK_BOT_TOKEN` to ensure that it starts with `xoxb-` by adding a print statement to your code?** I know you confirmed it in your `.env` above, but it would be good to know that it's also output in your app:

```python
print("SLACK_BOT_TOKEN:", os.environ.get("SLACK_BOT_TOKEN"))
```

In the meantime, I'll spend some time digging deeper into whether this another reason why you may be experiencing this problem.

**Comment by mwbrooks** [comment] 2021-06-08 22:17
@chxw would you mind also confirming that your `xoxb-` token matches the token on `api.slack.com/apps`? You may sometimes receive `not_allowed_token_type` if the previous token was revoked/expired/changed.

**Comment by chxw** [comment] 2021-06-09 15:34
Hi @mwbrooks, thanks for the quick response.

Wow you got it, I had previously run `source .env` when the .env file had an old/incorrect token, but after updating the .env file, I had forgotten to re-run `source .env`. What a silly issue! 

Thank you for help!

**Comment by mwbrooks** [comment] 2021-06-09 18:21
Hi @chxw, that's great to hear! Thanks for confirming that it was an invalid token.

>I guess now it's strange to think how the other function was working with an incorrect bot token?

Hmm, my best guess.... your signing secret was correct in your older sourced `.env`?

The `app_mention` events will be sent to your **Request URL**, which is your ngrok server. For each incoming request, Bolt [validates the request by checking the `X-Slack-Signature`](https://api.slack.com/authentication/verifying-requests-from-slack) against your `SLACK_SIGNING_SECRET`.

Since Slack allows you to regenerate your signing secret **separate** from your bot token, so there's a chance that your older `.env` still had your valid and original signing secret. That's just my best guess!

I'm going to close this issue, since we're figured out the `not_allowed_token_type` error. But feel free to respond about the `app_mention` event still triggering!

**Closed by mwbrooks** 2021-06-09 18:21 UTC
Labels: question
