### ISSUE TITLE
Custom attributes/properties to be passed back in the success_url after OAuth installation

### ISSUE THREAD

**Issue by robertlevy11** [slackapi/bolt-python#837] opened 2023-02-23 22:36 UTC
### Acceptance Criteria and Considered Solutions

Very similar question poised in the [bolt-js library here](https://github.com/slackapi/bolt-js/issues/1453).

**GOAL:** To link my company's internal client id to the `team_id` associated with the workspace in which a client has installed our Slack app.

**Ideal Approach:** Pass in the user's client id into the OAuth process such that we can create this mapping on the backend before the installation process returns.

**OK Approach:** Pass the user's workspace's `team_id` back to our authenticated Web app, such that a second request to our backend can be made to create this linking.

### Context of Product and Current Status of Solution

From our product, we have embedded an "Add to Slack" button.
After OAuth, we have the `success_url` in our `OAuthSettings` set to redirect the user back to the page of our app on which they originally hit "Add to Slack".

We have been using the `CallbackOptions` object to implement custom `success` and `failure` callbacks, but have not been able to figure how to provide the `team_id` in the `success_url` as a parameter.

### Ask
Please advise on the recommended approach to achieving the stated goal.

Thank you in advance.

**Comment by seratch** [comment] 2023-02-23 22:51
Hi @robertlevy11, thanks for asking the question!

>I have been using the CallbackOptions object to implement custom success and failure callbacks, but have not been able to figure how to provide the team_id in the success_url as a parameter.

The `success_url` option is available for quite simple use cases where the distination URL is static. So, in your case, you can use `callback_options.success` function to redirect an installing user to a URL with team_id and whatever.

Aside from the original question, I don't recommend using query string to transfer the `team_id` in this case because the approach is not secure enough. If an attacker sends a URL with an invalid team_id parameter to your end-user and the end-user visit the URL, your service may associate the end-user with an unexpected Slack workspace (meaning the attacker may be able to receive the end-user's information in their workspace for stealing confidential information).

Instead, I would suggest using a browser cookie to set the installing user's state as a preparation for the following user mapping process. If your app cannot use cookies for some reason (e.g., your app needs to redirect the use to a completely different domain URL), storing the Slack team_id to associate with the user's unique key (e.g., your service's user ID etc.) in your backend database would be an alternative good way.

I hope this helps.

**Comment by robertlevy11** [comment] 2023-02-23 23:01
Thanks @seratch I appreciate the quick response.
While investigating yesterday, I attempted the approach to set a cookie on the client's browser as follows:

```
def onSuccessfulInstall(args: SuccessArgs):
    """
    Callback to trigger on successful install
    """
    # generate default response
    response: BoltResponse =  args.default.success(args)
    # set custom header
    response.headers["Set-Cookie"] = f"slack-team-authed={args.installation.team_id}"
    # return response
    return response
``` 

However, I found that I could not access / find the cookie in my browser after redirection finished.

Is there another header, or method of setting the header that you recommend to accomplish this?

**Comment by seratch** [comment] 2023-02-23 23:11
>However, I found that I could not access / find the cookie in my browser after redirection finished.

Is the distination URL under the same domain? If not, this is an expected behavior of a web browser in general. If the URL is under the same domain, setting "Path=/;" may help. 

Overall, checking what this SDK does may be helpful to better understand a proper way to set the header: https://github.com/slackapi/python-slack-sdk/blob/v3.20.0/slack_sdk/oauth/state_utils/__init__.py

**Comment by robertlevy11** [comment] 2023-02-23 23:43
I now have the cookie setting properly, but it is on the wrong domain.

> Is the destination URL under the same domain? If not, this is an expected behavior of a web browser in general. If the URL is under the same domain, setting "Path=/;" may help.

Because the `/slack/install` endpoint and the `/slack/oauth_redirect` endpoint are rendered server-side, the domain receiving the cookie is the server domain that is serving these pages.

My web application is hosted at a different domain.

More specifically, during this development it is my localhost for web application and my exposed NGROK domain that is receiving the cookie.

I am investigating overriding the 200 status of the `BoltResponse` to see if I can get the cookie onto the proper domain using a 302 redirect. 

Are there any other strategies you recommend?

**Comment by seratch** [comment] 2023-02-23 23:54
As I already suggested above, you can store the mapping of slack team_id and the user's identity (slack user id, email address etc.) in your backend database. After redirecting your end-user to your main service domain URL, your main service can authenticate the user to identify who the user is (in other words, your main service must ask the user to log in with its account). With that, your app should be able to retrieve the team_id associated with the user identity from the database. Does this make sense to you?

If the domain difference can exist only for the local development, I would suggest running dev version of your web service on the same ngrok domain in some ways. For instance, having mock web service endpoint that is available only for local development. I don't think this is a difficulty specific to bolt-python, so you can discuss a reasonable way to do this with your team.

**Comment by robertlevy11** [comment] 2023-02-24 00:25
Yes thank you.
We are exploring both potential options of:

1. Running our App and Server on the same domain, or
2. Having the user additionally authenticate themself with Slack in order to create the mapping of our internal user id to their slack user_id

We appreciate your help in focusing our options.

**Comment by seratch** [comment] 2023-02-24 00:30
Glad to hear that my replies are helpful. I believe that everything about bolt-python side on this topic should be clear now. Would you mind if I close this issue now?

**Comment by robertlevy11** [comment] 2023-02-24 01:11
Not at all. Feel free to close.

**Closed** 2023-02-24 01:14 UTC
Labels: question

**Comment by racinger** [comment] 2023-05-24 10:23
Hi @robertlevy11 ,

Were you able to achieve your goal?

I have pretty much the same issue where my app and server are on different domains and I can't find a clean way to attach my internal customer id to their slack bot id.

Would you have a code sample or other advice?
