### ISSUE TITLE
Number input block kit element does not display on mobile

### ISSUE THREAD

**Issue by andybaumgar** [slackapi/bolt-python#903] opened 2023-05-27 04:14 UTC
#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

Python 3.9.0

#### OS info

IOS and Android

#### Steps to reproduce:

I tried the example in the [Block Kit docs](https://api.slack.com/reference/block-kit/block-elements?ref=bk#number) and that doesn't seem to work either.

### Expected result:

Shows numeric input on mobile like it has in the past.

### Actual result:

Does not show numeric input but instead "content cannot be displayed" message.  Still works on Desktop and browser.

**Comment by seratch** [comment] 2023-05-27 07:07
Hi @andybaumgar, thnaks for writing in! As mentioned in the document you've linked, currently the input block element is available only for modal views. It might be actually working on a channel message in the past, but now it's not officially supported. As a workaround, please consider opening a modal view for the interaction instead.

**Comment by andybaumgar** [comment] 2023-05-27 22:08
Thanks @seratch!  I believe we do use a modal view, sorry for the confusion.  I've attached an image.

![image](https://github.com/slackapi/bolt-python/assets/711780/22d0e5ac-82fb-420d-8671-7a3d7c87ff2e)

**Comment by andybaumgar** [comment] 2023-05-27 22:09
![image](https://github.com/slackapi/bolt-python/assets/711780/435e6ed4-8718-4d04-aa47-e9e0c7224ff5)

**Comment by seratch** [comment] 2023-05-29 02:20
@andybaumgar Thanks for sharing more details! I also managed to reproduce the issue with my iOS app (sorry, I haven't checked with Android app as I don't own any Android devices...). 

I just internally reported the issue to the mobile app development team. I cannot tell when the issue can be resolved for both mobile apps, but this should be resolved in future app releases.

**Comment by seratch** [comment] 2023-05-29 23:45
Hi @andybaumgar, I compiled an internal report on this matter yesterday, and the mobile app teams resolved the issue a few hours ago. The cause of the issue was feature flag configuration error (For some reason, the mechanism behaved unexpectedly, and the team will further investigate this to develop preventative measures), so reverting the configuration successfully resolved the issue for both iOS and Android clients.

I'll close this issue now. Thank you again for taking the time to report this problem, and we apologize for the disruption.

**Closed by seratch** 2023-05-29 23:45 UTC
Labels: bug, server-side

**Comment by andybaumgar** [comment] 2023-05-30 00:23
Thanks!
