### ISSUE TITLE
Block Kit (Emoji) not properly displaying on iphone, but correct on Mac, Android etc.

### ISSUE THREAD

**Issue by ManuelBuri** [slackapi/bolt-python#344] opened 2021-05-21 11:41 UTC
Hi, I am having the block kit below as an app home view and it does not properly show the emojis on iphones (see printscreens). What can I do to fix this?

```
{
   "type":"home",
   "callback_id":"app_home_view",
   "blocks":[
      {
         "type":"header",
         "block_id":"actions1",
         "text":{
            "type":"plain_text",
            "text":"Manuel's Overview 🗓",
            "emoji":true
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"_Select the week and book or find your bookings here._"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"Current Week",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":"Next Week",
                     "emoji":true
                  },
                  "value":"next-week"
               }
            ],
            "action_id":"select_week_app_home_view"
         }
      },
      {
         "type":"divider"
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Monday, 17/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day1_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Tuesday, 18/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day2_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Wednesday, 19/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day3_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Thursday, 20/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day4_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Friday, 21/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🏠 Working from home",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day5_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Saturday, 22/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day6_app_home_view"
         }
      },
      {
         "type":"section",
         "text":{
            "type":"mrkdwn",
            "text":"Sunday, 23/05/2021"
         },
         "accessory":{
            "type":"static_select",
            "placeholder":{
               "type":"plain_text",
               "text":"🤔 Not indicated",
               "emoji":true
            },
            "options":[
               {
                  "text":{
                     "type":"plain_text",
                     "text":":palm_tree: Out of office",
                     "emoji":true
                  },
                  "value":"1"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏠 Working from home",
                     "emoji":true
                  },
                  "value":"2"
               },
               {
                  "text":{
                     "type":"plain_text",
                     "text":"🏢 Unt. Haldenweg (5)",
                     "emoji":true
                  },
                  "value":"3"
               }
            ],
            "action_id":"select_day7_app_home_view"
         }
      },
      {
         "type":"divider"
      },
      {
         "type":"actions",
         "elements":[
            {
               "type":"button",
               "text":{
                  "type":"plain_text",
                  "text":"Office overview 🏢",
                  "emoji":true
               },
               "url":"https://example.com",
               "action_id":"user_overview"
            },
            {
               "type":"button",
               "text":{
                  "type":"plain_text",
                  "text":"Manage your account 🦸",
                  "emoji":true
               },
               "url":"https://example.com/",
               "action_id":"user_profile"
            },
            {
               "type":"button",
               "text":{
                  "type":"plain_text",
                  "text":"Manage your workspace 🗃️",
                  "emoji":true
               },
               "url":"https://app.example.com/office_profile/",
               "action_id":"workspace_settings"
            }
         ]
      }
   ]
}
```

<img src="https://user-images.githubusercontent.com/28053069/119131792-32ea0880-ba3a-11eb-85cd-4449c1487b99.jpg" width=300/><img src="https://user-images.githubusercontent.com/28053069/119131795-34b3cc00-ba3a-11eb-92f3-8827c24ad3a9.jpg" width=300/>

**Comment by misscoded** [comment] 2021-05-21 22:06
Hi @ManuelBuri! Thanks for bringing this issue to our attention. I've confirmed I also see this behavior on iOS. To cover all bases, can I ask you which iOS version you're using?

**Comment by ManuelBuri** [comment] 2021-05-22 09:55
Hi @misscoded , IOS version is 14.3 and the slack app is up-to-date as of yesterday. Thank you for your investigations :)

**Comment by seratch** [comment] 2021-05-22 12:58
@ManuelBuri Thanks for sharing the detailed info! It'd be helpful for the iOS team. By the way, I think you can use `:thinking_face:` instead of the emoji character 🤔 as a workaround. I'm sure that your app won't have the issue as long as it uses the emoji syntax in text properties.

**Comment by ManuelBuri** [comment] 2021-05-22 13:10
@seratch great idea... but I am **actually doing this already**...Github has transformed them to the emoji characters when I submitted my issue...

**Comment by misscoded** [comment] 2021-05-24 19:02
@ManuelBuri Just a bit of an update for you: I notified the folks that look after Block Kit and they indicated they'll look into it this week. It's a wonderful thing that you raised the issue, as the scope of this bug was thought to be limited to custom emojis and not all of them. So, thanks again for speaking up! 🙂 

Unfortunately, despite my best efforts, I've been unable to find a good workaround for the problem you're facing. Even when using a Block with a type of `input` with a `label`, there is a similar behavior. I recognize it's not ideal, but **for the time being and until it's fixed, I would recommend just not using an emoji in the `placeholder` > `text` value**.

**Comment by ManuelBuri** [comment] 2021-06-02 19:10
Hi slack team, any news?

**Comment by misscoded** [comment] 2021-06-02 20:40
Not yet. The ticket for this issue is still open and I'm unsure as to when that team will get around to resolving it. That said, I'm happy to report back when I get news that a fix has been introduced. 🙂

**Comment by ManuelBuri** [comment] 2021-06-03 19:05
sounds great @misscoded thanks a lot

**Comment by misscoded** [comment] 2021-06-03 21:39
I'm going to close this issue since the problem/fix is server-side and unrelated to Bolt, but do keep an eye on the changelog in the meantime. In the event that you happen to see a fix come through before we do, please feel free to drop a comment here!

**Closed by misscoded** 2021-06-03 21:39 UTC
Labels: server-side

**Comment by ManuelBuri** [comment] 2021-06-25 13:30
@misscoded any idea on when this gets fixed?

**Comment by misscoded** [comment] 2021-06-28 18:53
Nope, no updates to report at this time or estimation as to when it might be fixed.
