### ISSUE TITLE
Can't get events from AsyncApp

### ISSUE THREAD

**Issue by MihailovAlexander** [slackapi/bolt-python#1129] opened 2024-08-15 07:45 UTC
```
slack-bolt==1.18.1
slack_sdk==3.31.0
Python 3.11.9
Windows 10 Pro 10.0.19045
```
Hello.
I have a working synchronous application:
```python
import os
import socket
import traceback
from datetime import datetime, timedelta

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

token = os.getenv("SLACK_APP_TOKEN")
app = App(token=token)

# We track this event for messages from the bot to the channel
@app.event("message")
def handle_message_events(body, logger):
    print(body)


@app.event("reaction_added")
def handle_reaction_added_events(body, logger):
    print(body)

if __name__ == "__main__":
	SocketModeHandler(app, token).start()
```

Everything works fine here, print(body) works.
I want to add button functionality and for this I need Ack(). The documentation says that Ack() is best used in asynchronous mode. I tried to translate the code above into an asynchronous version and first took the code from the documentation:https://slack.dev/bolt-python/api-docs/slack_bolt/app/async_app.html#slack_bolt.app.async_app.AsyncApp.event

```python
import os
from slack_bolt.async_app import AsyncApp

app = AsyncApp(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)

# Listens to incoming messages that contain "hello"
@app.message("hello")
async def message_hello(message, say):  # async function
    # say() sends a message to the channel where the event was triggered
    await say(f"Hey there <@{message['user']}>!")

@app.event("message")
async def handle_message_events(body, logger):
    print(body)


@app.event("reaction_added")
async def handle_reaction_added_events(body, logger):
    print(body)

# Start your app
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

here everything starts without errors, however print(body) does not work for either reactions or messages.

I also tried to pass invalid data to token and signing_secret and the same result - the application starts and does not show any errors:

```
INFO:slack_bolt.AsyncApp:Bolt app is running!
======== Running on http://0.0.0.0:3000 ========
(Press CTRL+C to quit)
```

Step by step:
- I turned off my synchronous application
- I start the asynchronous one
- I go to the thread, add a reaction to the message or write a new message
- no reaction from the asynchronous application

**Comment by zimeg** [comment] 2024-08-17 06:40
Hey @MihailovAlexander 👋  Apologies for a delayed response! Right away I'm not sure why this wouldn't be working since the setup looks alright to me 🤔

> I also tried to pass invalid data to token and signing_secret and the same result - the application starts and does not show any errors

This is super strange to me, but I want to check a few other things first! I am curious if messages or events are received at all in these cases though - is it possible to check this with debug logging? 👀

```py
import logging

logging.basicConfig(level=logging.DEBUG)
```

Ideally some output will include a `payload` with incoming `reaction_added` events when these do happen.

Sometimes a "gotcha" of mine is forgetting to add the bot to channel when expecting events. As part of how the app exists in a workspace, the bot would have to be a channel member. Might be nice to check this too! 📚

Otherwise, I'm out of immediate ideas... I setup a similar app and am finding these listeners work as expected 😬

If anything seems strange in the logging or app setup with scopes and such, let me know! 🙏

**Comment by zimeg** [comment] 2024-08-17 06:42
I noticed the apps are changing from Socket Mode to HTTP connections too 😳  Perhaps something strange could be happening in this change?

**Comment by frieda-huang** [comment] 2024-08-17 19:38
Hi! I have the same issue as well! I also double checked the Event Subscriptions setup on the Slack app, Request URL is verified.

**Comment by frieda-huang** [comment] 2024-08-17 19:53
> Hi! I have the same issue as well! I also double checked the Event Subscriptions setup on the Slack app, Request URL is verified.

Just figured out the issue. I didn't add message.channels under the Application Settings as this post suggested https://stackoverflow.com/questions/65797289/why-cant-i-read-chat-messages-with-the-slack-bolt-library

After that, I also encountered the following issue, which I resolved by removing extra environmental variables, as suggested here: https://stackoverflow.com/questions/74716129/slack-bolt-python-although-the-app-should-be-installed-into-this-workspace-th

```
[SLACK BOLT PYTHON - Although the app should be installed into this workspace, the AuthorizeResult (returned value from authorize) for it was not found](https://stackoverflow.com/questions/74716129/slack-bolt-python-although-the-app-should-be-installed-into-this-workspace-th)
```

**Comment by MihailovAlexander** [comment] 2024-08-21 06:53
hi @frieda-huang ! Your examples are about a synchronous application. It works fine for me, I receive all types of events: messages, adding and deleting reactions. The problem starts when I try to convert this code to an asynchronous version.

**Comment by seratch** [comment] 2024-08-21 23:23
@MihailovAlexander As @zimeg mentioned, the biggest difference in your asyncio code is switching from Socket Mode to Rfequest URL hosting. Is this intentional and if yes, have you changed your app settings (https://api.slack.com/apps) to turn Socket Mode off and set a valid Request URL (public URL to receive requests from Slack API server)?

**Comment by MihailovAlexander** [comment] 2024-08-22 09:10
Hello, @seratch !
No, it was not done intentionally. Is it possible to run asynchronous mode in Socket Mode? Can you provide an example of such code?

**Comment by seratch** [comment] 2024-08-22 09:20
@MihailovAlexander Great to heat that it's the cause! Here is an example: https://github.com/slackapi/bolt-python/blob/main/examples/socket_mode_async.py Let me close this issue now, but whenever you have follow-up questions, please feel free to write in.

**Closed by seratch** 2024-08-22 09:20 UTC
Labels: question, area:async
