### ISSUE TITLE
Add canvases APIs to the WebClient

### ISSUE THREAD

**Issue by ijtrigoso** [slackapi/bolt-python#1106] opened 2024-07-02 17:02 UTC
Goal: 
Slack has added a new API (Create Canvases) and is yet to be added to the Slack Bolt Kit. 
Running the .client.conversations_canvases_create return the following error:
"""
AttributeError: 'WebClient' object has no attribute 'conversations_canvases_create'
"""

Link to Slack documentation:
https://api.slack.com/methods/conversations.canvases.create 

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by zimeg** [comment] 2024-07-02 19:49
Hey @ijtrigoso! 👋  Thanks for raising this issue! A change to the underlying SDK introduced the `conversations.canvases.create` method in slackapi/python-slack-sdk#1508 and we'll get started on a release to Bolt Python super soon 🚀

On the current `v1.19.0` these methods can still be called using a [string argument for the method name](https://slack.dev/python-slack-sdk/web/index.html#calling-any-api-methods). It's a bit more prone to misspelling, but should be calling this API as intended! Hope this helps for now 🙏

**Comment by zimeg** [comment] 2024-07-02 20:06
Oops! I thought the SDK version was fixed in Bolt but it seems to offer [a range](https://github.com/slackapi/bolt-python/blob/main/requirements.txt) of supported SDK versions!

I tested the following snippet with a new Bolt app and the latest version of the SDK `v3.30.0` and found that it works with the right scopes and channel ID:

```py
client.conversations_canvases_create(
    channel_id="C0123456789",
    document_content={
        "type": "markdown",
        "markdown": "hello!"
    }
)
```

If it's possible to bump the SDK version you're using, this method should be unlocked! 🚀

Didn't mean to cause confusion with that first response, but I'll go ahead and close this issue as **Done** since this method is available with the right changes. Please do feel free to follow up with any other questions though!

**Closed by zimeg** 2024-07-02 20:06 UTC
Labels: question, dependencies

**Comment by ijtrigoso** [comment] 2024-07-02 20:58
You are right, thank you! I updated my Slack Bolt and forgot about Slack-SDK.

**Comment by rajmayank** [comment] 2024-07-25 11:13
For anyone looking into this, use the following snippet



```python
from slack_sdk import WebClient
from slack_bolt import App

...
...

app = App(client=WebClient(SLACK_BOT_TOKEN))

...
...
```


As of 25-Jul-24, here are the package versions I'm using
```
slack_bolt==1.19.1
slack_sdk==3.31.0
```
